"""add_ingestion_telemetry

Revision ID: 23d2b3f6346e
Revises: bf29f0ad0c0f
Create Date: 2025-12-29 12:40:08.641778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23d2b3f6346e'
down_revision: Union[str, Sequence[str], None] = 'bf29f0ad0c0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_documents', sa.Column('ingestion_method', sa.String(), nullable=True))
    op.add_column('financial_documents', sa.Column('ingestion_logs', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_documents', 'ingestion_logs')
    op.drop_column('financial_documents', 'ingestion_method')
    # ### end Alembic commands ###
