"""Add reconciliation fields

Revision ID: 269e9991d46d
Revises: 45e125995a0b
Create Date: 2025-12-06 19:52:19.121323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '269e9991d46d'
down_revision: Union[str, Sequence[str], None] = '45e125995a0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('receipt_id', sa.UUID(), nullable=True))
    op.add_column('transactions', sa.Column('match_score', sa.Float(), nullable=True))
    op.add_column('transactions', sa.Column('match_type', sa.String(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'financial_documents', ['receipt_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'match_type')
    op.drop_column('transactions', 'match_score')
    op.drop_column('transactions', 'receipt_id')
    # ### end Alembic commands ###
