"""make_transaction_date_nullable

Revision ID: 5651daa2d9d6
Revises: 23d2b3f6346e
Create Date: 2025-12-29 19:05:05.029812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5651daa2d9d6'
down_revision: Union[str, Sequence[str], None] = '23d2b3f6346e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
