"""Add original_filename

Revision ID: 99e827f68f11
Revises: c602e630e87b
Create Date: 2025-12-06 22:12:22.127096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99e827f68f11'
down_revision: Union[str, Sequence[str], None] = 'c602e630e87b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_documents', sa.Column('original_filename', sa.String(), server_default='unknown.pdf', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_documents', 'original_filename')
    # ### end Alembic commands ###
