"""Add token tracking columns

Revision ID: b90319ba66c9
Revises: cd3d53e65ae0
Create Date: 2025-12-27 20:55:13.447034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b90319ba66c9'
down_revision: Union[str, Sequence[str], None] = 'cd3d53e65ae0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tax_analysis', sa.Column('prompt_tokens', sa.Integer(), nullable=True))
    op.add_column('tax_analysis', sa.Column('completion_tokens', sa.Integer(), nullable=True))
    op.add_column('tax_analysis', sa.Column('total_tokens', sa.Integer(), nullable=True))
    op.add_column('tax_analysis', sa.Column('estimated_cost', sa.Float(), nullable=True))
    op.add_column('tax_analysis', sa.Column('model_version', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tax_analysis', 'model_version')
    op.drop_column('tax_analysis', 'estimated_cost')
    op.drop_column('tax_analysis', 'total_tokens')
    op.drop_column('tax_analysis', 'completion_tokens')
    op.drop_column('tax_analysis', 'prompt_tokens')
    # ### end Alembic commands ###
