"""Add BRL cost tracking

Revision ID: bf29f0ad0c0f
Revises: b90319ba66c9
Create Date: 2025-12-27 22:12:31.192990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf29f0ad0c0f'
down_revision: Union[str, Sequence[str], None] = 'b90319ba66c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tax_analysis', sa.Column('estimated_cost_brl', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tax_analysis', 'estimated_cost_brl')
    # ### end Alembic commands ###
