"""Add file_hash

Revision ID: c602e630e87b
Revises: 269e9991d46d
Create Date: 2025-12-06 21:04:00.855156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c602e630e87b'
down_revision: Union[str, Sequence[str], None] = '269e9991d46d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_documents', sa.Column('file_hash', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'financial_documents', ['file_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'financial_documents', type_='unique')
    op.drop_column('financial_documents', 'file_hash')
    # ### end Alembic commands ###
