"""Add tax persistence fields

Revision ID: cd3d53e65ae0
Revises: cfb6ad884599
Create Date: 2025-12-27 19:41:45.861873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd3d53e65ae0'
down_revision: Union[str, Sequence[str], None] = 'cfb6ad884599'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tax_analysis', sa.Column('risk_level', sa.String(), nullable=True))
    op.add_column('tax_analysis', sa.Column('raw_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tax_analysis', 'raw_analysis')
    op.drop_column('tax_analysis', 'risk_level')
    # ### end Alembic commands ###
