"""Add TaxAnalysis table

Revision ID: cfb6ad884599
Revises: 99e827f68f11
Create Date: 2025-12-26 17:12:41.955940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfb6ad884599'
down_revision: Union[str, Sequence[str], None] = '99e827f68f11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_analysis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('classification', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('month', sa.String(), nullable=True),
    sa.Column('justification_text', sa.Text(), nullable=True),
    sa.Column('legal_citation', sa.String(), nullable=True),
    sa.Column('is_manual_override', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tax_analysis')
    # ### end Alembic commands ###
